### ISSUE TITLE
Enhance the aggregator to automatically include source bundles when aggregating all the contents of a repository

### ISSUE THREAD

**Issue by merks** [eclipse-cbi/p2repo-aggregator#13]
When aggregating all contents of a repo, only features and their transitive requirements are included automatically  This can miss corresponding source bundles as seen here:

https://github.com/eclipse-platform/eclipse.platform.releng/pull/182

It would be better when aggregating all contents that for any included IU, the corresponding source IU, if it existing is also aggregated.

This will address the following issue:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/739

**Comment by merks** [comment]
There is now support for Aggregator.includeSources.  When set to true, for all the IUs to be aggregated, it checks if there exists an available corresponding source IU and if so includes that in the to-be-aggregator IUs.

**Comment by merks** [comment]
@jonahgraham

We may wish to use this for the SimRel aggregator.   If the platform progressively stops including source features or gradually stops including 3rd party libraries in features, the corresponding source IUs will no longer be aggregated.  I tested this feature, and an additional ~1,700 IUs would be included for SimRel.  What do you think?  (I expect quite a few consumers use the train repository to build target platforms.)

**Comment by jonahgraham** [comment]
> We may wish to use this for the SimRel aggregator. 

Please make the change for SimRel. It is incredibly frustrating to ever be in a situation where the source bundles aren't available and I agree that many people use SimRel as the sole source for Eclipse when building their apps.
